### ISSUE TITLE
"Loading GLAD failed"

### ISSUE THREAD

**Issue by kahrkunne** [borodust/bodge-glad#2]
I'm trying to get trivial-gamekit to run, and I've managed to track the issue down to this package.

Steps to reproduce:
```
(ql:quickload :bodge-glad)
(bodge-glad:init)
```

Backtrace: https://pastebin.com/CDyXsXtv

System information:
Arch Linux
NVIDIA 415.25 drivers
GTX 1050 TI GPU

**Comment by borodust** [comment]
`#'init` must be called within valid OpenGL context. Calling it anywhere else will result in an error. What was the original issue?

**Comment by kahrkunne** [comment]
What about this then:

```
(ql:quickload :trivial-gamekit)
(gamekit:defgame test () ())
(gamekit:start 'test)
```

Gives: https://pastebin.com/JcEYsXJU
Continuing from there gives: https://pastebin.com/rDZdcHvi

**Comment by borodust** [comment]
Hmm, that's interesting.
What does `glxinfo | grep 'OpenGL core profile version'` print?

**Comment by kahrkunne** [comment]
```~ $ glxinfo | grep 'OpenGL core profile version'                                               
OpenGL core profile version string: 4.6.0 NVIDIA 415.25
```

**Comment by borodust** [comment]
Okay, lets try latest dist:
```
(ql-dist:install-dist "http://bodge.borodust.org/dist/org.borodust.bodge.testing.txt")
(ql:update-all-dists)
```
And try again after restarting an image (sbcl).

**Comment by borodust** [comment]
If that won't work, there might be quirks i need to work around for nvidia blob.

**Comment by kahrkunne** [comment]
Oh for Christ's sake, I know what it is now:
```WARNING: GLFW error 65544: X11: Failed to open display :1```
For some reason, something sets $DISPLAY to ":1" on X startup for me, even though my X server is running on :0. This breaks some programs, including this apparently. I had forgotten.

So it's an issue on my system, sorry for bothering you!

**Comment by borodust** [comment]
No probs, glad it works now, or does it?

**Comment by kahrkunne** [comment]
Yes, a quick `(setenv "DISPLAY" ":0")` in Emacs managed to fix it. Thanks for your help, doubt I'd have figured it out without using the latest dist (which printed that error message for me)!
